routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});



Route::resource('home','HomeController');
Route::resource('sopir','SopirController');
Route::resource('tpp','TppController');
Route::resource('tpa','TpaController');

Route::resource('test','TestController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/tpa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class tpa extends Model
{
	protected $table = 'tb_tpa';
    //
}

app/Http/Controllers/TpaController.php
<?php

namespace App\Http\Controllers;

use App\tpa;
use Illuminate\Http\Request;

class TpaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $tpa=Tpa::orderBy('id','desc')->get();
        return view('tpa.index',compact('tpa'));
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\tpa  $tpa
     * @return \Illuminate\Http\Response
     */
    public function show(tpa $tpa)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\tpa  $tpa
     * @return \Illuminate\Http\Response
     */
    public function edit(tpa $tpa)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\tpa  $tpa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, tpa $tpa)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\tpa  $tpa
     * @return \Illuminate\Http\Response
     */
    public function destroy(tpa $tpa)
    {
        //
    }
}

resources/views/tpa/create.blade.php
create.blade.php

resources/views/tpa/edit.blade.php
edit.blade.php

resources/views/tpa/index.blade.php
@extends('template.master')
@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Tempat Pembuangan Akhir
			<!-- <small>advanced tables</small> -->
		</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li><a href="#">Tables</a></li>
			<li class="active">Data tables</li>
		</ol>
	</section>

	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-xs-12">


				<div class="box">
					<div class="box-header">
						<h3 class="box-title">Data Tempat Pembuangan Akhir</h3>
						<div class="box-tools pull-right">
							<a href="{{ route('tpp.create')}}" class="btn btn-primary btn-sm btn-flat">

								Tambah Data
							</a>
						</div>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<table id="example1" class="table table-bordered table-striped">
							<thead>
								<tr>
									<th>No</th>
									<th>Nama Tempat</th>
									<th>Latitude</th>
									<th>Langitude</th>
										
										
										<th>Action</th>
									</tr>
								</thead>
								<tbody>

									<?php $no=1; ?>
									<?php foreach ($tpa as $dt): ?>



										<tr>
											<td class="text-center"><?php echo $no++ ?></td>
											<td>{{$dt->nama_tempat}}</td>
											<td>{{$dt->latitude}}</td>
											<td>{{$dt->longitude}}</td>
											
											
											<td class="text-center" style="width:150px;">
												<form method="POST" action="" accept-charset="UTF-8">
													<a href="" class="btn btn-primary btn-sm btn-flat" >
														Edit
													</a>
													<input name="_method" type="hidden" value="DELETE">
													<input name="_token" type="hidden" value="{{ csrf_token() }}">
													<input type="submit" class="btn btn-danger btn-sm btn-flat" onclick="return confirm('Anda yakin akan menghapus data ini?');" value="Hapus">

												</form>
											</td> 
										</tr>

									<?php endforeach ?>

								</tbody>
							</table>
								
							</div>
							<!-- /.box-body -->
					</div>
						<!-- /.box -->
					</div>
					<!-- /.col -->
				</div>
				<!-- /.row -->
			</section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->



		<!-- jQuery 3 -->
		<script src="{{asset('assets/backend/bower_components/jquery/dist/jquery.min.js')}}"></script>
		<!-- Bootstrap 3.3.7 -->
		<script src="{{asset('assets/backend/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
		<!-- DataTables -->
		<script src="{{asset('assets/backend/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
		<script src="{{asset('assets/backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
		<!-- SlimScroll -->
		<script src="{{asset('assets/backend/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
		<!-- FastClick -->
		<script src="{{asset('assets/backend/bower_components/fastclick/lib/fastclick.js')}}"></script>
		<!-- AdminLTE App -->
		<script src="{{asset('assets/backend/dist/js/adminlte.min.js')}}"></script>
		<!-- AdminLTE for demo purposes -->
		<script src="{{asset('assets/backend/dist/js/demo.js')}}"></script>
		<!-- page script -->
		<script>
			$(function () {
				$('#example1').DataTable()
				$('#example2').DataTable({
					'paging'      : true,
					'lengthChange': false,
					'searching'   : false,
					'ordering'    : true,
					'info'        : true,
					'autoWidth'   : false
				})
			})
		</script>
	

	@endsection